Bellman-Ford Algorithm

In [96]:
import numpy as np

In [56]:
G={
    's':[('u',2),('v',5)],
    'u':[('s',1),('v',2)],
    'v':[('t',-2)],
    't':[]
}


In [62]:
def BFA(G,inicial):
    d=[]
    for i in range(len(G.keys())):
        d.append({})
        
    for j in list(G.keys()):
        if j==inicial: 
            d[0][j]=0
        else:
            d[0][j]=float('inf')
            
            
    for k in range(1,len(G.keys())):
        for b in list(G.keys()):
            R=reverse_graph(G)
            d[k][b]=min(d[k-1][b] , min(list(  (  d[k-1][R[b][i][0]]+R[b][i][1] for i in range(len(R[b]))   )   )  )   )
                        
    return d

In [61]:
def reverse_graph(G):
    R={}
    for i in list(G.keys()):
        R[i]=[]
    
    for i in list(G.keys()):
        for p in G[i]:
            R[p[0]].append((i,p[1]))
    return R

reverse_graph(G)

{'s': [('u', 1)], 't': [('v', -2)], 'u': [('s', 2)], 'v': [('s', 5), ('u', 2)]}

In [63]:
BFA(G,'s')

[{'s': 0, 't': inf, 'u': inf, 'v': inf},
 {'s': 0, 't': inf, 'u': 2, 'v': 5},
 {'s': 0, 't': 3, 'u': 2, 'v': 4},
 {'s': 0, 't': 2, 'u': 2, 'v': 4}]

In [29]:
a='#INTENTION'
b='#EXECUTION'

In [135]:
def Dis(a,b):
    M=np.zeros((len(a),len(b)))
    N=np.zeros((len(a),len(b)))
    for i in range(1,len(a)):
        M[i,0]=i
    for i in range(1,len(b)):
        M[0,i]=i
    
    for i in range(1,len(a)):
        for j in range(1,len(b)):
            if a[i]==b[j]:
                M[i,j]=min(M[i-1,j]+1,M[i,j-1]+1,M[i-1,j-1])
            else:
                M[i,j]=min(M[i-1,j]+1,M[i,j-1]+1,M[i-1,j-1]+2)
    i,j=len(a)-1,len(b)-1
    k=M[i,j]
    N[i,j]=1
        
    
    print(M)
    print(N)
 
    


In [136]:
Dis(a,b)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  2.  3.  4.  5.  6.  7.  6.  7.  8.]
 [ 2.  3.  4.  5.  6.  7.  8.  7.  8.  7.]
 [ 3.  4.  5.  6.  7.  8.  7.  8.  9.  8.]
 [ 4.  3.  4.  5.  6.  7.  8.  9. 10.  9.]
 [ 5.  4.  5.  6.  7.  8.  9. 10. 11. 10.]
 [ 6.  5.  6.  7.  8.  9.  8.  9. 10. 11.]
 [ 7.  6.  7.  8.  9. 10.  9.  8.  9. 10.]
 [ 8.  7.  8.  9. 10. 11. 10.  9.  8.  9.]
 [ 9.  8.  9. 10. 11. 12. 11. 10.  9.  8.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [137]:
def Dis2(a,b):
    M=np.zeros((len(a),len(b)))
    N=np.chararray((len(a),len(b)),dtype='str')
    ptr=['deletion','insertion','substiution']
    for i in range(1,len(a)):
        M[i,0]=i
    for i in range(1,len(b)):
        M[0,i]=i
    
    for i in range(1,len(a)):
        for j in range(1,len(b)):
            if a[i]==b[j]:
                L=[M[i-1,j]+1,M[i,j-1]+1,M[i-1,j-1]]
                min=L[0]
                for i in range(len(L)):
                    if L[i]<min:
                        M[i,j]=
                        
                    
            else:
                M[i,j]=min(M[i-1,j]+1,M[i,j-1]+1,M[i-1,j-1]+2)           
    print M
    print N

In [151]:
N=np.chararray((len(a),len(b)))

In [156]:
N

chararray([[b'\xd8', b'\xdb', b'!', b'\x1f', b'\x18', b'\x7f', '', '',
            b'@', b'e'],
           [b'\x12', b'\x02', '', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', '', '', ''],
           ['', '', '', '', '', b'r', '', '', '', ''],
           ['', '', '', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', b'p', '', '', '']], dtype='|S1')

In [155]:
N[5,5]="rapolho"

In [157]:
data = np.array([['a','b'],['c','d']])

In [160]:
data


array([['a', 'b'],
       ['c', 'a']], dtype='<U1')

In [159]:
data[1,1]='abc'

Knapsack

In [88]:
weights=[6,2,4,3,11]
values=[20,8,14,13,35]

In [133]:
ueit=[1,2,3]
valei=[1,4,6]

In [144]:
def unb_knapsack(capacity, weights, values):   #Unbounded Snapsack
    W=capacity
    n=len(weights)
    K={}
    K[0]=0
    items={}
    items[0]=[]
    for x in range(1,W+1):
        K[x]=0
        items[x]=[]
        for i in range(n):
            if weights[i]<=x:
                a=K[x]
                K[x]=max(K[x],K[x-weights[i]]+values[i])
                if K[x]!=a:
                    items[x]=items[x-weights[i]]+[i]
    return K

In [145]:
unb_knapsack(10,weights,values)

{0: 0, 1: 0, 2: 8, 3: 13, 4: 16, 5: 21, 6: 26, 7: 29, 8: 34, 9: 39, 10: 42}

In [147]:
def zeroumknapsack(capacity, weights, values):  #0/1 knapsack
    W=capacity
    n=len(weights)
    K=np.zeros((W+1,n+1))
    
    for x in range(1,W+1):
        for j in range(1,n+1):
            K[x,j] = K[x,j-1]   #igual ao anterior
            if weights[j-1]<=x:
                K[x,j] = max(K[x,j],K[x-weights[j-1],j-1]+values[j-1])  #max entre o anterior na linha e o outro 
    
    return K[W,n]

#Obs: esse ta com a matriz transposta em relação ao do exemplo nos sildes 
#

In [148]:
zeroumknapsack(10,weights,values)

35.0

In [142]:
zeroumknapsack(3,ueit,valei)

array([[0., 0., 0., 0.],
       [0., 1., 1., 1.],
       [0., 1., 4., 4.],
       [0., 1., 5., 6.]])