Bellman-Ford Algorithm

In [7]:
import numpy as np

In [56]:
G={
    's':[('u',2),('v',5)],
    'u':[('s',1),('v',2)],
    'v':[('t',-2)],
    't':[]
}


In [43]:
def BFA(G,inicial):
    d=[]
    for i in range(len(G.keys())):
        d.append({})
        
    for j in list(G.keys()):
        if j==inicial: 
            d[0][j]=0
        else:
            d[0][j]=float('inf')
            
            
    for k in range(1,len(G.keys())):
        for b in list(G.keys()):
            d[k][b]=min(d[k-1][b] , min(list(   (d[k-1][G[b][p][0]]+G[b][p][1] for p  in range(len(G[b])) )   )  )   )
                        
    return d

In [59]:
def reverse_graph(G):
    R={}
    for i in list(G.keys()):
        R[i]=[]
    
    for i in list(G.keys()):
        for p in G[i]:
            R[p].append(i)
    return R

reverse_graph(G)

KeyError: ('u', 2)

In [44]:
BFA(G,'s')

ValueError: min() arg is an empty sequence

In [30]:
[G['s'][i][0] for i in range(len(G['s']))]

['u', 'v']

In [39]:
min(3,4)

3

In [48]:
gen=(d[1][G['s'][p][0]]+G['s'][p][1] for p  in range(len(G['s'])))

In [49]:
list(gen)

NameError: name 'd' is not defined

In [29]:
a='#INTENTION'
b='#EXECUTION'


In [135]:
def Dis(a,b):
    M=np.zeros((len(a),len(b)))
    N=np.zeros((len(a),len(b)))
    for i in range(1,len(a)):
        M[i,0]=i
    for i in range(1,len(b)):
        M[0,i]=i
    
    for i in range(1,len(a)):
        for j in range(1,len(b)):
            if a[i]==b[j]:
                M[i,j]=min(M[i-1,j]+1,M[i,j-1]+1,M[i-1,j-1])
            else:
                M[i,j]=min(M[i-1,j]+1,M[i,j-1]+1,M[i-1,j-1]+2)
    i,j=len(a)-1,len(b)-1
    k=M[i,j]
    N[i,j]=1
        
    
    print(M)
    print(N)
 
    


In [136]:
Dis(a,b)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  2.  3.  4.  5.  6.  7.  6.  7.  8.]
 [ 2.  3.  4.  5.  6.  7.  8.  7.  8.  7.]
 [ 3.  4.  5.  6.  7.  8.  7.  8.  9.  8.]
 [ 4.  3.  4.  5.  6.  7.  8.  9. 10.  9.]
 [ 5.  4.  5.  6.  7.  8.  9. 10. 11. 10.]
 [ 6.  5.  6.  7.  8.  9.  8.  9. 10. 11.]
 [ 7.  6.  7.  8.  9. 10.  9.  8.  9. 10.]
 [ 8.  7.  8.  9. 10. 11. 10.  9.  8.  9.]
 [ 9.  8.  9. 10. 11. 12. 11. 10.  9.  8.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [137]:
def Dis2(a,b):
    M=np.zeros((len(a),len(b)))
    N=np.chararray((len(a),len(b)),dtype='str')
    ptr=['deletion','insertion','substiution']
    for i in range(1,len(a)):
        M[i,0]=i
    for i in range(1,len(b)):
        M[0,i]=i
    
    for i in range(1,len(a)):
        for j in range(1,len(b)):
            if a[i]==b[j]:
                L=[M[i-1,j]+1,M[i,j-1]+1,M[i-1,j-1]]
                min=L[0]
                for i in range(len(L)):
                    if L[i]<min:
                        M[i,j]=
                        
                    
            else:
                M[i,j]=min(M[i-1,j]+1,M[i,j-1]+1,M[i-1,j-1]+2)           
    print M
    print N

In [151]:
N=np.chararray((len(a),len(b)))

In [156]:
N

chararray([[b'\xd8', b'\xdb', b'!', b'\x1f', b'\x18', b'\x7f', '', '',
            b'@', b'e'],
           [b'\x12', b'\x02', '', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', '', '', ''],
           ['', '', '', '', '', b'r', '', '', '', ''],
           ['', '', '', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', '', '', '', ''],
           ['', '', '', '', '', '', b'p', '', '', '']], dtype='|S1')

In [155]:
N[5,5]="rapolho"

In [157]:
data = np.array([['a','b'],['c','d']])

In [160]:
data


array([['a', 'b'],
       ['c', 'a']], dtype='<U1')

In [159]:
data[1,1]='abc'